name: Humanitec

on: push

jobs:
  pipeline:
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push to Humanitec
        uses: humanitec/build-push-to-humanitec@v1
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          organization: aiven

